### ISSUE TITLE
Creating Wumpus World

### ISSUE THREAD

**Issue by AnimeshSinha1309** [AnimeshSinha1309/AimaJavascript#1]
# Contribution to Chapter 7 and 13
This is a visualisation of the Wumpus World needed for the Logic agent in Chapter 7 and the Probability Inferences in Chapter 13.

# Current State
The Present version of this is extremely rudimentary and implemented in [Chapter 7 on the Website](http://aimacode.github.io/aima-javascript/7-Logical-Agents/)
![wumpus](https://user-images.githubusercontent.com/9739218/49940736-6be73000-ff06-11e8-998c-7a9ba4ffa09e.png)

# Plans
*This is Just for the Logic Agent Segment in Chapter 7*

* Have Each Block show 2 things
  - The Measurement: *Stinch or Breeze* (telling us if there is Wumpus or a Pit nearby)
  - The Inference: What can be in the block - *Wumpus, Pit, Both, or is it safe?*
* Remove the Explicit Dots
  - The Player should not be able to see where exactly Wumpus / Pits / Gold are.
* Have a table of Inferences below
  - For all 16 squares, the current state and possible inferences that can be drawn from it.
  - These possibilities keep getting narrower as more information about measurements comes in

**Comment by AnimeshSinha1309** [comment]
![screenshot from 2018-12-13 18-46-58](https://user-images.githubusercontent.com/9739218/49941100-7eae3480-ff07-11e8-976d-1bf0f8db802b.png)
This is an implementation of the probability agent idea in the UC Berkeley Course. The Outer Rim (Used Here) can be used to show what the measurement was, **Stinch(w), Breeze(p), Both (wp) or Safe ()**, and the Inner portion of the square can be used to signal our inferences. i.e. **Wumpus (W), Pit (P), Both (WP), or Nothing ()**.

We can choose to represent these as:
* 4 Colors with a color key on Outer and Inner Rim. Outer rim has measurements, inner has inferences.
* Two halves of the square having labels of W and P. Upper half has measurements, lower has inferences.

The good thing about the color and rim arrangement is that it makes it easier to see that the measurements affect the square next to it. But the label and halves arrangement make it easier to read the labels and see the propositional logic.

**Comment by GaurangTandon** [comment]
I was thinking of the following:

 - rim color indicates the measurement
 - text inside the square indicates inferences. i.e. Wumpus (W), Pit (P), Both (WP), or Nothing ().

Also, as you said, when I implement the grid I should have to expose some methods for you to use. Can you elaborate what would those methods be? Afaict, there are two buttons in the UCB dialog you've shown above, and also some information top-right. What do those do and are those the only API methods you would need, or are more required?

**Comment by AnimeshSinha1309** [comment]
No no, We need very different API. Each Grid must be an object. And That grid object must have as one of its instance variables an array of small block objects. Each of the small block objects must provide `setMeasurement(measurement)` and `setInference(inference)`. Also, we must have a marker showing where we are, like the green dot in the current game and a way to move it, but that maybe later. Finally we need a **Click Event Listener**, `onclick(function callback(x : int, y : int))`

We will need to scale this as we go along. On the probability chapter, we will need to change our inferences with are W or no W, to 0.86 W form, color the background to give a feel of what the gradient is like, and maybe even make our grid bigger. So, 4 x 4 may not suffice. Let's try to be as flexible as can be, cause this model of the world spans many chapters and gives us great power, even if we don't implement those chapters.

**Comment by GaurangTandon** [comment]
Thanks for the additional information, that will certainly help me build a better API. On it.

**Comment by AnimeshSinha1309** [comment]
This is what my SVG outline looks like. See if you can use the SVG library to improve it. The DOM thing works, and my implementation is similar, but SVG-TypeScript combo seem to give more flexibility.
![wumpusworld](https://user-images.githubusercontent.com/9739218/50035576-f1630100-0028-11e9-9d00-0d174fd44aa2.png)
Having Labels inside is the goal now. Then we can start thinking of a propositional logic agent.
**For Documentation on the SVG Manipulation, check: [SVGjs](https://svgjs.com/docs/2.7/getting-started/)**

**Comment by GaurangTandon** [comment]
I need to know what exactly were the flexibility issues in the previous files to be sure I won't reintroduce the same issue again. 

- I didn't use the `class` syntax because of lack of support of private variables.
- I don't understand why we need SVG instead of DOM.
- I also don't get the need to start from scratch.

And that's probably because I haven't played the game yet. Please give me a link to whichever implementation on the internet is closest to your thoughts and I'll play it first.

**Comment by AnimeshSinha1309** [comment]
I have implemented the full version, please take a look at the **[demo here](https://animeshsinha1309.github.io/AimaJavascript/7-Logical-Agents/)**. Closing out this issue.
